service:
  name: MobileappReleaseRss

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    FEED_URL: ${env:FEED_URL}

functions:
  MobileappReleaseRss:
    handler: handler.MobileappReleaseRss
    memorySize: 128
    timeout: 20
    logRetentionInDays: 90
    events:
      - http:
          method: get
          path: '/'
